version: 2

registries:
  github:
    type: git
    url: https://github.com
    username: x-access-token
    password: ${{secrets.DEPLOYBOT_PACKAGES_READ_WRITE_TOKEN}}

updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    registries:
      - github
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
