version: 2

registries:
  private_packagist:
    type: composer-repository
    url: https://repo.packagist.com/inpsyde/
    username: token
    password: ${{secrets.PACKAGIST_TOKEN}}
  github:
    type: git
    url: https://github.com
    username: x-access-token
    password: ${{secrets.DEPLOYBOT_PACKAGES_READ_WRITE_TOKEN}}

updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    registries:
      - private_packagist
      - github
    cooldown:
      default-days: 3
      semver-major-days: 14
    groups:
      composer-security:
        applies-to: security-updates
        patterns: ["*"]
      composer-production:
        applies-to: version-updates
        dependency-type: "production"
        update-types: ["minor", "patch"]
      composer-development:
        applies-to: version-updates
        dependency-type: "development"
        update-types: ["minor", "patch"]
  - package-ecosystem: "npm"
    directory: /
    schedule:
      interval: "weekly"
      day: "monday"
    cooldown:
      default-days: 3
      semver-major-days: 14
    groups:
      npm-security:
        applies-to: security-updates
        patterns: ["*"]
      npm-production:
        applies-to: version-updates
        dependency-type: "production"
        update-types: ["minor", "patch"]
      npm-development:
        applies-to: version-updates
        dependency-type: "development"
        update-types: ["minor", "patch"]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    cooldown:
      default-days: 3
    groups:
      github-actions-security:
        applies-to: security-updates
        patterns: ["*"]
      github-actions-updates:
        applies-to: version-updates
        update-types: ["minor", "patch"]
