name: Create Release Asset

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout released version
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer
          coverage: none

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v3
        with:
          composer-options: '--prefer-dist'

      - name: Install dependencies
        run: yarn

      - name: Build assets
        run: yarn build

      - name: Create plugin zip
        run: yarn plugin-zip

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: ./inpsyde-google-tag-manager.zip
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOYBOT_REPO_READ_WRITE_TOKEN }}
