name: Create Release Asset

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_REGISTRY_TOKEN }}
    steps:

      - name: Checkout released version
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer
          coverage: none

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          NODE_VERSION: '20'
          registry-url: 'https://npm.pkg.github.com/'

      - name: Github Packages Auth
        run: |
          npm config set @inpsyde:registry 'https://npm.pkg.github.com'
          npm config set //npm.pkg.github.com/:_authToken ${{ secrets.DEPLOYBOT_PACKAGES_READ_ACCESS_TOKEN}}

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v3
        with:
          composer-options: '--prefer-dist'

      - name: Install dependencies
        run: npm install

      - name: Build assets
        run: npm run-script build

      - name: Create plugin zip
        run: npm run-script plugin-zip

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: ./inpsyde-google-tag-manager.zip
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOYBOT_REPO_READ_WRITE_TOKEN }}
