name: E2E Testing

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - 1.x
      - 2.x
  pull_request:
    branches:
      - master
      - 1.x
      - 2.x

# Cancels all previous workflow runs for pull requests that have not completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name for pull requests
  # or the commit hash for any other events.
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  e2e-playwright:
    uses: inpsyde/reusable-workflows/.github/workflows/test-playwright.yml@run-script
    strategy:
      matrix:
        php: [ '8.2' ]
    with:
      PHP_VERSION: ${{ matrix.php }}
      ARTIFACT_INCLUDE_HIDDEN_FILES: true
      ARTIFACT_OVERWRITE: true
      ARTIFACT_PATH: './artifacts'
      NODE_VERSION: 20
      PLAYWRIGHT_BROWSER_ARGS: 'chromium --with-deps'
      SCRIPT_NAME: 'e2e'
    secrets:
      COMPOSER_AUTH_JSON: '${{secrets.PACKAGIST_AUTH_JSON}}'
      GITHUB_USER_EMAIL: ${{ secrets.DEPLOYBOT_EMAIL }}
      GITHUB_USER_NAME: ${{ secrets.DEPLOYBOT_USER }}
      GITHUB_USER_SSH_KEY: ${{ secrets.DEPLOYBOT_SSH_PRIVATE_KEY }}
      NPM_REGISTRY_TOKEN: ${{ secrets.DEPLOYBOT_PACKAGES_READ_ACCESS_TOKEN}}
