name: E2E Testing

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - 1.x
      - 2.x
  pull_request:
    branches:
      - master
      - 1.x
      - 2.x

# Cancels all previous workflow runs for pull requests that have not completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name for pull requests
  # or the commit hash for any other events.
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  e2e-playwright:
    name: Playwright
    runs-on: ubuntu-latest
    env:
      GITHUB_USER_EMAIL: ${{ secrets.DEPLOYBOT_EMAIL }}
      GITHUB_USER_NAME: ${{ secrets.DEPLOYBOT_USER }}
    strategy:
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        env:
          GITHUB_USER_SSH_KEY: ${{ secrets.GITHUB_USER_SSH_KEY }}
        if: ${{ env.GITHUB_USER_SSH_KEY != '' }}
        with:
          ssh-private-key: ${{ env.GITHUB_USER_SSH_KEY }}

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        env:
          COMPOSER_AUTH: '${{ secrets.COMPOSER_AUTH_JSON }}'
        with:
          php-version: 8.2
          tools: composer
          coverage: none

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v3
        with:
          composer-options: '--prefer-dist'

      - name: Set up node
        uses: actions/setup-node@v4
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_REGISTRY_TOKEN }}
        with:
          node-version: '20'
          registry-url: 'https://npm.pkg.github.com/'
          cache: 'npm'

      - name: Github Packages Auth
        run: |
          npm config set @inpsyde:registry 'https://npm.pkg.github.com'
          npm config set //npm.pkg.github.com/:_authToken ${{ secrets.DEPLOYBOT_PACKAGES_READ_ACCESS_TOKEN}}

      - name: Install dependencies
        run: npm ci

      - name: Npm build
        run: npm run-script build

      - name: Install Playwright dependencies
        run: |
          npx playwright install chromium --with-deps

      - name: Install WordPress and start the server
        run: |
          npm run-script wp-env start

      - name: Run the tests
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
        run: |
          xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- npm run-script test:e2e

      - name: Archive debug artifacts (screenshots, traces)
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: artifacts
          path: ./artifacts
          if-no-files-found: ignore
