name: InstaWP WordPress Testing

on:
  push:
    branches:
      - insta-wp-built

jobs:
  create-wp-for-testing:
    runs-on: ubuntu-latest
    steps:
      - uses: instawp/wordpress-testing-automation@main
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          INSTAWP_TOKEN: ${{secrets.INSTAWP_TOKEN}}
          INSTAWP_TEMPLATE_SLUG: google-tag-manager
          REPO_ID: 542
          INSTAWP_ACTION: create-site-template
